### PR TITLE
Unicode Mode and colors!

### PR DESCRIPTION
**Pull request by mistBourne1300**
Added unicode mode and spooky colors to wm-refactor (for realzlies this time)

### CODE REVIEW

**Comment by natecraddock** [comment]
I get a crash on Mate Terminal on the lab machines

```
File "/users/guest/n/nathanzc/projects/zygrader/zygrader/ui/window.py", line 108, in __init_colors
    curses.init_pair(8, CURSES_ORANGE, curses.COLOR_BLACK)
_curses.error: init_pair() returned ERR
```

It looks like some terminals don't support extra colors

**Comment by mistBourne1300** [comment]
hmm... Is there a way we can check what terminal is running? maybe `os.system("echo $TERM")`?

**Comment by natecraddock** [comment]
It looks like this might be a bigger issue, so I'd rather hold off on this until after 5.0.0.

There might be ways to determine from curses if the terminal supports setting colors.

**Review by natecraddock — CHANGES_REQUESTED** [review]
I did not test, but I'm fairly certain this will crash on `Mate Terminal` because `curses.can_change_color()` is a function, not a variable, so this if statement will always be true because functions are truthy.

**Comment by natecraddock** [comment]
#56 is replacing this.

**Pull request closed without merging**
